version: "3.9"

networks:
  baconstation-network:
    driver: bridge

volumes:
  baconstation-data:
    driver: local

services:

  mongo:
    image: mongo
    container_name: baconstation-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    networks:
      - baconstation-network
    volumes:
      - baconstation-data:/data/db
  
  db-tools:
    image: lironer/mongodb-tools
    container_name: baconstation-dbtools
    restart: always
    ports: 
      - 27018:27018
    networks:
      - baconstation-network
    command: tail -F anything

  grafana:
    image: grafana/grafana-oss
    container_name: baconstation-grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - baconstation-network
