networks:
  baconstation-network:
    driver: bridge

volumes:
  baconstation-data:
    driver: local

  baconstation-export:
    driver: local

  baconstation-grafana:
    driver: local

services:

  mongo:
    image: mongo
    container_name: baconstation-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    networks:
      - baconstation-network
    volumes:
      - baconstation-data:/data/db
  
  db-tools:
    build:
      context: .
      dockerfile: baconstation-exporter.dockerfile
    container_name: baconstation-exporter
    restart: always
    ports: 
      - 27018:27018
      - 8080:8080
    environment:
      USERNAME: $MONGO_INITDB_ROOT_USERNAME
      PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    networks:
      - baconstation-network
    volumes:
      - baconstation-export:/data
    command: tail -F anything

  grafana:
    image: grafana/grafana-oss
    container_name: baconstation-grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks:
      - baconstation-network
    volumes:
      - baconstation-grafana:/data
