services:

  mongo:
    image: mongo
    container_name: baconstation-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    network: baconstation-network
    volumes:
      - baconstation-data:/data/db
  grafana:
    image: grafana/grafana-oss
    container_name: baconstation-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    network: baconstation-network

volumes:
  baconstation-data:
    driver: local

